# Actions Data Exploration
In this notebook we'll explore the different `actionType`s that compose the data obtained from the live `PlayByPlay` endpoint.

In [8]:
import pandas as pd
from pathlib import Path

In [9]:
SEASON_ID = '22024'
GAME_ID = '0022400630'

In [10]:
data_path = Path("~/MBAI/data").expanduser()
season_path = data_path / f"rs{SEASON_ID}"
game_path = season_path / f"g{GAME_ID}"
pbp_path = game_path / "playbyplay"

In [11]:
df = pd.read_csv(pbp_path / "actions.csv")

In [12]:
df

,clock,timeActual,period,actionType,subType,personId,x,y,possession,scoreHome,...,jumpBallRecoveredPersonId,jumpBallWonPersonId,jumpBallLostPersonId,shotDistance,shotResult,blockPersonId,assistPersonId,officialId,foulDrawnPersonId,stealPersonId
0,0 days 00:12:00,2025-01-25 00:10:48.500000+00:00,1,period,start,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0 days 00:11:57,2025-01-25 00:10:50.500000+00:00,1,jumpball,recovered,203995.0,NaN,NaN,1.610613e+09,0,...,203995.0,1631109.0,1642270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0 days 00:11:37,2025-01-25 00:11:10.200000+00:00,1,2pt,DUNK,1631109.0,8.88,51.97,1.610613e+09,0,...,NaN,NaN,NaN,3.25,False,1642270.0,NaN,NaN,NaN,NaN
3,0 days 00:11:37,2025-01-25 00:11:10.200000+00:00,1,block,NaN,1642270.0,NaN,NaN,1.610613e+09,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0 days 00:11:34,2025-01-25 00:11:13.200000+00:00,1,rebound,defensive,1642270.0,NaN,NaN,1.610613e+09,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0 days 00:00:10.700000,2025-01-25 02:30:23.300000+00:00,4,2pt,DUNK,1631109.0,94.06,51.72,1.610613e+09,95,...,NaN,NaN,NaN,0.93,True,NaN,1630182.0,NaN,NaN,NaN
607,0 days 00:00:03.300000,2025-01-25 02:30:35.800000+00:00,4,2pt,DUNK,1641739.0,7.44,52.70,1.610613e+09,95,...,NaN,NaN,NaN,2.20,True,NaN,1629014.0,NaN,NaN,NaN
608,0 days 00:00:00,2025-01-25 02:30:44.700000+00:00,4,2pt,Layup,1631109.0,94.44,47.06,1.610613e+09,97,...,NaN,NaN,NaN,1.47,True,NaN,1641733.0,NaN,NaN,NaN
609,0 days 00:00:00,2025-01-25 02:30:53.700000+00:00,4,period,end,NaN,NaN,NaN,1.610613e+09,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,0 days 00:00:00,2025-01-25 02:30:57.900000+00:00,4,game,end,NaN,NaN,NaN,NaN,97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df['actionType'].unique()

array(['period', 'jumpball', '2pt', 'block', 'rebound', '3pt', 'foul',
       'substitution', 'timeout', 'turnover', 'steal', 'freethrow',
       'violation', 'game'], dtype=object)

In [14]:
action_subtypes = {
    action: action_df['subType'].unique().tolist()
        for action, action_df in df.groupby('actionType')
}

action_subtypes

{'2pt': ['DUNK', 'Jump Shot', 'Layup', 'Hook'],
 '3pt': ['Jump Shot'],
 'block': [nan],
 'foul': ['personal', 'offensive', 'technical'],
 'freethrow': ['1 of 2', '2 of 2', '1 of 1'],
 'game': ['end'],
 'jumpball': ['recovered'],
 'period': ['start', 'end'],
 'rebound': ['defensive', 'offensive'],
 'steal': [nan],
 'substitution': ['out', 'in'],
 'timeout': ['full'],
 'turnover': ['out-of-bounds',
  'traveling',
  'lost ball',
  'bad pass',
  'offensive foul',
  'shot clock'],
 'violation': ['kicked ball',
  'defensive goaltending',
  'lane',
  'delay-of-game']}